apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-mern-app-frontend.fullname" . }}-deployment
  labels:
    {{- include "simple-mern-app-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "simple-mern-app-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-mern-app-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
