apiVersion: apps/v1
kind: Deployment
metadata: 
  name: simple-mern-app-backend-deployment
  labels:
    app: simple-mern-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-mern-app-backend
  template:
    metadata:
      labels:
        app: simple-mern-app-backend
    spec:
      containers: 
      -  name: simple-mern-app-backend
         image: sohaibm/simple-mern-app-backend:1.0.1
         ports:
         - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: simple-mern-app-backend-service
spec: 
  selector: 
    app: simple-mern-app-backend
  type: 
    LoadBalancer
  ports: 
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30112
